## 問題説明 ##
MongoDBバージョン3.6のインスタンスはデータベースを繰り返しドロップ（削除）した後、同じ名前のデータベースを作成し、このデータベースを読み取り・書き込みまたはドロップすると「database does not exist」エラーが表示されます。詳細については下図に示すとおりです。<br>
![](https://main.qcloudimg.com/raw/58381d2c50010a332c9ceb241a0062dd.png)
## ソリューション ##
この問題は共通問題です。この問題が発生する原因はmongosのmetadata cacheが更新されていないことです。詳細については公式[説明](https://docs.mongodb.com/manual/reference/method/db.dropDatabase/)を参照してください。下図に示すとおりです。<br>
![](https://main.qcloudimg.com/raw/5372e96b216c15f4bb597904bf9961aa.png)
ソリューションは2つあります、**どちらかを選んでください**：<br>
1. mongosを再起動します。この操作はコンソールで行います。下図を参照してください。<br>
![](https://main.qcloudimg.com/raw/0ab109e9a0adad49c3d96660132ea290.png)
2. または[flushRouterConfig](https://docs.mongodb.com/manual/reference/command/flushRouterConfig/#dbcmd.flushRouterConfig)コマンドを実行します。その中に詳細な説明が添付されます。

